services:
  sql:
    container_name: sql-1
    image: mcr.microsoft.com/azure-sql-edge
    platform: linux/arm64  # Specific for M1/M2 Macs
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
      - MSSQL_PID=Developer
      - MSSQL_PLATFORM=Linux
      # Memory settings
      - MSSQL_MEMORY_LIMIT_MB=4096
      - MSSQL_TELEMETRY_ENABLED=FALSE
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    cap_add:
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          memory: 4GB
        reservations:
          memory: 2GB
    restart: unless-stopped

  redis:
    container_name: redis-1
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
  sql-data: